ALTER TABLE `oxactions`
ADD `OXPIC`   VARCHAR(128) NOT NULL DEFAULT '' AFTER `OXACTIVETO`,
ADD `OXPIC_1` VARCHAR(128) NOT NULL DEFAULT '' AFTER `OXPIC`,
ADD `OXPIC_2` VARCHAR(128) NOT NULL DEFAULT '' AFTER `OXPIC_1`,
ADD `OXPIC_3` VARCHAR(128) NOT NULL DEFAULT '' AFTER `OXPIC_2`,
ADD `OXLINK`   VARCHAR(128) NOT NULL DEFAULT '' AFTER `OXPIC_3`,
ADD `OXLINK_1` VARCHAR(128) NOT NULL DEFAULT '' AFTER `OXLINK`,
ADD `OXLINK_2` VARCHAR(128) NOT NULL DEFAULT '' AFTER `OXLINK_1`,
ADD `OXLINK_3` VARCHAR(128) NOT NULL DEFAULT '' AFTER `OXLINK_2`;
